apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-migration-connection
  namespace: field-data-api
spec:
  encryptedData:
    db: AgAh+hk3uufO22Ebo7z48YfG9407wbtqaQnpc/wg2lpoL96F+QMecEn4+J/mNjmyqTRAbIr/BFjhVhkJGr6MfYJ63tnBM1UJtBwf6OzxunasKB1lQk+aPlt5sDOs+f/WiAiLizuN1KzGTbUbXgosjhRYCWBGeuTw4D5OHNAShOtukjpc760H8Y43tBntSPNU45fs399r/ZaVr21JF3Er4EzV7CJAIFm27mSJ11mpqGQrCL8+RQcy03Q5cwku2zUpfGVwTafKUbY+dfSmIBKDB0uZISjT6p3sH8nUEVlNwEzWE0cMybl2jm4LXp54UyHAvcGLDL4m9lADIqNj5uW2k+1m6jymIeoPbtyeO/w2a4gnAjD/Ov/Fa+6WDYwTMHoGKET8p3qJZP3W9xc2u6TyUd8bv4mEqKQkOsIOoYUdmCkflc66GSXASjvYDuT2bZgt7SYZLR47/szBK4zgtYL+cDRVTHivzRaeSrhho3E0NrwSq3xRfwIRxytBdNeC91Q+HOaoR1mnp71lwhzwFeZnYTdZTehhBemvZZEJhtel6U/Z35qDDsCmWK9mx/3dIekmrEwmA0Cv2Q+hXSd3WwB70ftn4c/NVLbrENssj+PgT0OWSrHF4xK7w+pOEOt18//fRThi5KQEzHGctTRqB3zMFVxcv7xe+EtdAIYN2K0igxix3IkBLPtBgqAH1LJFNL59+Lae44P0fQjOFEmLuGDxcTxyydgAU1WcFgTZnaKqSW6AkOY11JWHEPKqjh9BZkwoU7yAcFpB4843zLWZP+2x5KNqDOfNDXOdYuh2K0VqdJVFEhEBf8+R+qD/DxWR/eYEtqbO8ys0NJc/f43az/G3q89ErMX1CkfsdM/sMzWfsAvxlAEv/5VXixQKWaBLZi4k0ksyp7mGc9DBMjbC
  template:
    metadata:
      creationTimestamp: null
      name: database-migration-connection
      namespace: field-data-api

