apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-connection
  namespace: field-data-api
spec:
  encryptedData:
    messageQueue: AgANBU/049rqQ5HzN1tREdIWush174viVJtESbIB6ocG/G8I9e96buqcLabLls7pL4wTcdn64Vo78LA7ROguKMMuEjOhSGQXHAjTN3udQD+dJTRLYicK5coRDWUcn9+j+yaZDtP7Zfs3xAjz8qtsff46A12bxDoyVJsHg0kqe2WAgxQFrFP2a3bJEGZiffJ7DEUXgT3tGIiSqGO7TbqbYh8KCxCT02GhOubSg1m+2LPPEBTf0d66RSO3scFOM902w4v+YFR+7mH1py8+CgP7EDdJHknhihJBu+DkkNZS9WjYY12YRxF6o+hk74+5Y8nBQygmuFm+8CkX6L4DLkREhaw3KJAC1lEofdGBPiX+395G/3kLHzy5rDKPE7HQrOw6+arFN0JvTtL3qlVQ6HSF5XqNRMaPU6aJviecsZTSD9jCsgns4iKcEFkxM/O30+jutrPvOx0A753Gqu5Cz7fnouAhvmHeSBvL8cJ5dmyD7vhX2evRcsqJUdT8Z6srLHyvRD0yDj8QLf0AUB0ev8jFxaJyuYa70QMsBilfkhwO3+8HrSQAgs2XT3eNnufQe5mW+jW2wpv3d4XSN3ZMfwhnqhdWsu5zN8jGL7h4PgbUn2/ORS1Bnxq+JLb3QhAmtR1hQL5wqee1WeGija5se7IrhLOn9du/sejWdpu1iMRkRIcHn5CcDOki1RT74ErKx0cvINrq2d+pGvtaf5M3UZc/8UXGSJibt8eK8EJKNXn8YzO3Ld5YThsWur9zDHGbKDxCt5zZiTS6QPC1I8XKTHVQuCCX6cQSOHiRwmdg9Cmdf68MoWuGEAexm9qtGjmOHFPuGkJ1r6+n0s46Ti5BUtMasw==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-connection
      namespace: field-data-api
