apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-migration-connection
  namespace: field-data-api
spec:
  encryptedData:
    db: AgCVCAmGqoulI16nS8frtqM+u4jRCxU9FkQIGgQPmJf0e+dcCiUGYnYGLkRENnEB9UYxa1sPa3Qf7qZxHx1KpRoecNMbx0IsHpIUlhi3/lxzlX4QRaYhRe1VqWhXPr1o72FqNS3KNFj9ffjvK2Lv49B5q9hBSWSZ4mHi1j2Gu5fjvInp4AaS5zI14TIyu3T//f0QXy2PIdGfJ2qdqMTySinlnkWPeMfXEOp1Pdo9DSsq8xEBG7kbuiFFJ4fP4zKWR+LOiGS0/19Xnz/FbYJNBg++LTQwoDICsJNnFyNZ8zJSKoYQjz2FyN1uNNky13wo0lPb1k9ESdHC0Kfh2NKUd+Kp7qwo+Y5vBaVYd+GL80aHpwXWTUXcf50AU1S0zjYxFL3i7N4PIS9rbnNRadOR+QivY3DvrZo5Sl3iAQQZKRerssz+XG8zPEsVYwB4TXBOtCwK45K507sD4B3h3PnQmqIvxWSh9xeOpJQ3R4AS2s0IJOuSUb350r39pYC4mD6qj/2R42cBR/SW4zN+gmXQ29T11ifJE5i33d5z/hqaSjd40BrSvWf87QGk3BB3tJtfuQNBmp5PleDA15CioPdQmw3DYlGNDyE/EUA7Thlu6pBw7wB6NEl8kC4PKMU/RyDHwLGrxMWu0SS5jaBt+pn14K7abi0bY5bgcM/35hjr/pgBJlynbBggv0QDh7jsJ8Wbf0uu8xnQdIBxcuUEkkkqHvlrmVyfyZDOVm2ofk9Z0b7IDNMVagHWSwUDpYlc4cWhyKSxtc2Uz6B1EKbA1eTTcY/8L2R7sYxtkqyL+yCAhM/7g2AWWRIJCJVOa1dqDezbv7T1yWQVRhgxwS59h6x/at2B3n9YWmlnZg2k7czqLMpLoKdyMpPvjyEMcwmZ+xwhflYYeVY5D9q4A8xpFCCeGEA=
  template:
    metadata:
      creationTimestamp: null
      name: database-migration-connection
      namespace: field-data-api

