apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-migration-connection
  namespace: field-data-api
spec:
  encryptedData:
    db: AgBRnDGBgL7E0oURx/UHEr00tkyF1nkNG202GKJvnrf6pWMaHEIHRkE8EuI/7M4WiA2eFD1p24d+y4G+GeHFB8swl/EHL7Pkw3/cjuIghSxkkb2w/hZ8+t6WtwjWi4wmLy9cEgwibzQ43M3vz63R8oZhK6FRGNc87NAmjtk5nGa2l6ajlaNPetG/XrUaYsJLMX81TlA8ZMSieCnuwBo8/m+Arcj1Bx/vqqKTfkJ9Bxsm3km5hotvV6oTD9cVun5vw0tKhmlx/3+LCU6bPkVIt5O6ZjCxZfVYdwUhukLNWG/M0wnUjR4UZXndRx5NUxa/FVEyqKYDXSaIcsAkcj5wFGctamc9KfnDVCzlwFegXu1GzHThxF4Atbe2FEV1lyPc032YonqgF/lWHgy0BIc3dGAVbsCAW1xmy8+DGX8rV4QFAgCPj1Y15OHaEN4gJ/M3gq8mLfWhdG4GkvxIfyQN4A58Adjifgud0hRUbbrXInzJs9OdycK17AT2zTBLATMkjMdQRJeDCod6raW0cWq/G7au6b+ZcXaHsi6ie5SMhvsYzlQzXb6raqOWfusXu3CgJLjRMWmmKvhqCSx5j7UrX7AaVOBBHkGNAb6pRjvyGTarCsN/NHqd3A406AbYmCwDMD4FFSfVt5yZwCv+qeRHt/PCxDy/mchJ+q7XaM/2QJRP5Xd+uDHddpJW0GgcnNekHQQKcon1Z3ydnDL0E0m8zhXkNXO90wzx6btV964ay628fzEFRXunRgbfr5UVhIiobrT+qJ+iGL+x0x7006j6nVlqLypoCbPpWFEi8ew/oQT4EeFR5at51GndnI+gPre+ehjt39EUDZdeaO95Gf5sza18m7j3wGNr65H45L7YKlSeZtqfQWMpkl7LtD+Kpx18OeEf4Rxqpw2ilc1VrgRqvoE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: database-migration-connection
      namespace: field-data-api

