apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-migration-connection
  namespace: field-data-api
spec:
  encryptedData:
    db: AgAFfdXe5eqBfkoqNY4sRvxVGqoZyQVKpD6Bq3NYRwqQOVKFiXdr3HkXIN9hPwTNoHST5d75iR4voRhqYIkbf8koIaaLMP6MmJuI5cXzTUpzCT8mJiB7bzhaXmjdGJMnfFHmn6NAX03FahoFa9GE7mlc6XjCVYoZ0nJ8hGFpRqbWD2FJWBW+705qJb2xtt8FhUljWBwhO6JXA2a2OzH0TcqP+d+mx27cicm/TTiuTs8CbRwXKi83XcuGZOAHdrKjcIkIlJb7yXYFH6OO/rzCCiiMpUwRvSrkyDwJ7qWYh3czB/6NNsDSzGM1h3ZnN3NHaQwmwY7V7A9fiGHli39ma+p3Q/foiE5ce58z8Qp7hgqF7Uywza79xxb1Oexex3ySdwqTO6VX+NQS63axPf5qW72/T6u5RCeZ4HtX2U9kziaOqHxCdNNbphwn+T88qTw4LX74njsyvgbEVddSQM0213aVYQNZOgiHJqriyQbxQh2jhYMaPg0TO3y81C6kKF5i72PQlhHDAu3qOXUelegwcLiEDtYx+icdGFL5/IoOD0f4T/rqkBS1mdCwbwXhlwQYQQxMWhasyMZlUv/3EW30WqZLzU2g3hfb4YWjDYXFtU8cLkfQOhj0qiLlWeNuSuKoBMXPjn31GAvVwS8Z+3NsJEwxkFxyikg7EAVw09V8xEJ+EParEXLU0R8NhaLUXU897eSxmu59io5rR3M54u3Vo7gwcYiGYjA/qdQgtfpNwijDD9aExm0y9To5Vaq0D0Fbitwyhw5BncuhPPvU4u7+56Gs0nxAJMv10861uQZy7ZXBxn3gLLlhEaCmrQWwrnx7+GniIXbkCoEduV030RMJlVlIptf3HsG5gx0TSZ6ysJv33Ra1NszAYFROvaJ2xbmB+Kl8+Vd4Tbhskij1sZRySqs=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: database-migration-connection
      namespace: field-data-api

