patchesStrategicMerge:
- rabbitmq-connection-sealed-secret.yaml
- database-connection-sealed-secret.yaml
- database-migration-connection-sealed-secret.yaml
images:
- name: greenstand/treetracker-field-data
  newTag: 1.10.4
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
