apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-connection
  namespace: rabbitmq-cluster
spec:
  encryptedData:
    messageQueue: AgAixYt5GyVHNbllRzFdxVYrghbdx+gmG0ktPu6wrEr/n7tgszQNE17xiVausAf7yoVQl46zm1j7ukv0v3mHoQl3JMj1un73BG+f1kw2TgekqYlSKFHGVt4iJWipbhQdqhtA+1ZEULRlqO6XJ3J9fpXqu+yUu4zhkT9nytWVyzd29e7VoHiOY2Cm34//uhaCl8FgjKrPIqX6uqoObRzJElBQKkoSPMiLzj0BXDwN9/YzZm9qrqxutJ8dbrPEJEqKaQrXVo0aJwOx9mqcHU5uiCLOFPHSyWwUMEJgPpLzkPcCSKhY2gEO5ufhAkalq7ji/3e22j3WRuTZ0bkF4VgA9hShN4YyWyeczeR1pP5igyxVSrwJ+rH5PPkpj40jRKPvWBicE5lN3ZeMQjEHPk/jGeI6zntGjymG0OrcHjQXUz/AbdV4cdBd0TgSywkP2YQmprNsJ6TmAPm+iatuD2C2kEmdqaSVjXVVqmp4HZj6v5779Ca+DHdU33l9S6BXNplDP+yAhQWx2McqzdesNHplhJRdZJ+TBsRW0sLk+EmoZ1chkJpENmcjWkrKvZB47g8kUQPCN+02xxxXbeII+RAR2ptHhcTUBWQh1lgTgyDz6WbFB/JbDBi5QtxeJFkCDkoqB+gMrEwjReWkMDdfmSUp4+Uqc1qnS/oaVaBRLW05E+VkXEDD2nrgYYjKv3drEZgjOLx5kUJw4CvKlvxgLhoXDQKZRBh/7NJPOpH/0P0timXH9G3jPPBKdCwXRbZgbA6430DASL2qfT0e4E0a+d5Nr+WBJZusPiQ4dijPC5qiaIoxXDinKC0dYwAUPzxaXY/p3j6YQdDqyCCNlBjC3EcMug==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-connection
      namespace: rabbitmq-cluster

