apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetracker-field-data
  labels:
    app: treetracker-field-data
spec:
  replicas: 2
  selector:
    matchLabels:
      app: treetracker-field-data
  template:
    metadata:
      labels:
        app: treetracker-field-data
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: doks.digitalocean.com/node-pool
                    operator: In
                    values:
                      - microservices-node-pool
      containers:
        - name: treetracker-field-data
          image: greenstand/treetracker-field-data:latest
          ports:
            - containerPort: 3006
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-connection
                  key: db
            - name: DATABASE_SCHEMA
              value: field_data
            - name: DATABASE_URL_LEGACYDB
              valueFrom:
                secretKeyRef:
                  name: database-connection
                  key: db
            - name: RABBIT_MQ_URL
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-connection
                  key: messageQueue
