apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: treetracker-rabbitmq-connection
spec:
  encryptedData:
    messageQueue: AgDWRQO+vdwQm3iujE+2mYIm3U2nI6L+ycqF1Sz7cjg9aCApA2xSy80VGtaAH5j+X85SuqMLXm2eex0TEwXrlKVajlHg4Os+zt8XcDMCNzt0B2/9PxIOV5eJ2sK0XRRj0U77SyMZBShJLE5MMZVxzAcJFGvcLp0pM11w3eS92KKEAqbdTSfUcPM+85tHfq6oCbdpqawNtaG+SDBapsRl7YrHhsefEd8wx4eiXzPkMo5TIr3N9Ud6GxjC5VQk+Z7vgmT5Bf7eIEPSQLqqPuGkOOLQNkQguy52o4kGYdp9zDhudig3AmbvelUQdV4dLW5kbFjuB3xlSiUuVTKokqNAQU1ABuG6t+mqoSJQ24Y5Q8Mx/ia1Kp3R4O7gvGfvUbVxIolzIknRhJ877Mz2DcD+QJHGfVGJFw71qk4seQI0d3QR0KHo0J4ynOcH88qUJvi6n3K3X7ToRIg3riaCfesyCf6+1QZr+hv5YBw2MZshGkZYLvL1CirCjI5yw8b32U94XmS+W3HIfWH+QUNlggQtwwwG/50DQQcredyDzY+eHOBfQm+9tMpQHaxA/nHZ6aG5ioKNFT+iif1N+gVCD/lub85H43tVRKcl7jhSLiOrDyPBzxDBerwB5Ttf2UCB4tbQN574RwUzdhO6NBUsRaFlfzZ+r3mjGvW1eUedVu24PzdKq503pgW/YRFPS7yP+EJGN2Hh7VAazo1qCWJssPtuQ9ZWMp2Vl7hRvVc3zPnpRD6XlYyQNbas+mYJ+8phfFximBl95scxyh9fhtJhzQCs7wwfr2MvwOD/Uxnd+eIeiPZdPTAQDxtfHbkR3IorO3k=
  template:
    metadata:
      name: treetracker-rabbitmq-connection

