apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-connection
  namespace: rabbitmq-cluster
spec:
  encryptedData:
    messageQueue: AgBUFB1jMiac4Wq2sWEfPp+wCfCau2+cJw0GYrDE+v+sW/q18TDwW1b72J4JOCqu55OPyeo0hHBaQbLVijAcrUF+4IzfpQ9x+0/NZXoepmRNjdyRZU+5jTIBUA17dNgalqRubrexCOrFli3NJnRovXr8BtfA7q0iSJuOoMqWTsPHYRPlCB7X2QDwI+tuyuAVHEQY2zMgZPtV2waqiFHiTW53LLiKud72dVicApZJLaKTj/0ZsaxKZ+WSMGGwbvKGAUMmhv/vBJ4PeqjDaLAWutxUsO/o9E2dxxa4VDmSeEOhWTxX5Hi2YTTuxXQwlp/FDZ+86uxtU/OlLQikxHSTkMM86klmz5F6pyaIaezIkSUGKJtN0LegAJ9I8Vjjly1dcBOHSQo4QUpLfaHloO4DwIb5qGC1fF5DOkDdJbA4dhWW169TE9O5+AnT3welIVDOej3VuQcseE/JR8ShjoSAPtjJs7AFnbmrnb4PLJImTKJx/2qTNf94e8GrRyDMidWzpQdeeL3w6+RbsjrKY/qa1lgracLbIj0sqyeyJoBOJrbs9/NiwZPNGSTC1yutcSw7uCd3OA60yJvFmhygJX+ER4WTWm6C/umDmhkzjDjsV/dJHPOAEVrJ8+KZsuG+hwuEgygePtdZzpdTa2bP6n9p/R5uZHUH1Kcbo9fmZpHu6U5hOCXLCpMBg7dmjGfAaQ4gHdEgVGrf5UqtPGSrhVMrzXXFdN2SiVq0sFwxEarsuGn9RIVPyhG01BjNg8SS26jkgKBH9HXnlN3W2nv1FhlutsLQ4KLmBMv1B2RProz2bYnI/OYeqt7v7u2blF/OxSlfXimeKERvauRzAiIYfXf01w==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-connection
      namespace: rabbitmq-cluster

