openapi: 3.0.3
info:
  title: API
  version: '1.0'
  description: ''
  x-logo:
    url: ''
paths:
  /captures:
    description: >-
      A list of http methods that supports creation, retrieval, and update of
      capture data.
    summary: Operations supported for captures resource
    get:
      tags: []
      operationId: getCaptures
      summary: >-
        Retrieves capture data based on a filtering criteria or without
        filtering criteria
      parameters:
        - in: query
          example: ''
          required: false
          deprecated: false
          allowEmptyValue: false
          description: >-
            The status of the capture data, it can be one of the following
            three 

            * unprocessed

            * approved

            * rejected
          x-last-modified: 1611167306743
          type: object
          enum: []
          properties: {}
          name: status
        - name: planter_contact
          in: query
          example: ''
          required: false
          deprecated: false
          allowEmptyValue: false
          description: "Search capture data containing planter's email or phone number "
          x-last-modified: 1611167296641
        - name: planter_id
          in: query
          example: ''
          required: false
          deprecated: false
          allowEmptyValue: false
          description: Retrieve capture data with the given planter_id
          x-last-modified: 1611167349326
        - name: limit
          in: query
          example: ''
          required: false
          deprecated: false
          allowEmptyValue: false
          description: >-
            The number of captures to retrieve, this defaults to 1000 if not
            specified.
          x-last-modified: 1611167795903
        - name: offset
          in: query
          example: ''
          required: false
          deprecated: false
          allowEmptyValue: false
          description: >-
            To paginate the results, use `offset` to skip the number of records
            that has already been consumed by prior API invocations. For e.g. if
            there are 100 capture records and each invocation has `limit` value
            set to 10, an incrementing `offset` value by  10 would paginate to
            show all 100 records in 10 invocations. The first one with no
            offset, second invocation with 20, third with 30, and all the way to
            last one with offset value of 90.
          x-last-modified: 1611168282092
      description: >-
        Retrieves capture data based on a filtering criteria or without
        filtering criteria. Result is in the form of an array of capture
        objects. Pagination is supported by utilizing the `limit` and `offset`
        parameters.
      responses:
        '200':
          type: ''
          description: ''
          content:
            application/json:
              encoding: ''
              schema:
                example:
                  - id: d6d6e901-f7eb-49ab-bf78-44727bd18e8b
                    reference_id: '213083'
                    image_url: nothing
                    lat: '1.3425'
                    lon: '34.342'
                    planter_id: '227'
                    planter_contact: gstracker@gmail.com
                    attributes:
                      entries:
                        - key: dbh
                          value: ''
                        - key: abs_step_count
                          value: '-1'
                        - key: delta_step_count
                          value: '0'
                        - key: rotation_matrix
                          value: >-
                            0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
                    status: unverified
                    created_at: '2021-01-16T01:37:01.046Z'
                    updated_at: '2021-01-16T01:37:01.046Z'
                  - id: cd2cbfa8-7203-41aa-966f-b844167e8df3
                    reference_id: '213081'
                    image_url: nothing
                    lat: '1.3425'
                    lon: '34.342'
                    planter_id: '227'
                    planter_contact: growth@gmail.com
                    attributes:
                      entries:
                        - key: dbh
                          value: ''
                        - key: abs_step_count
                          value: '-1'
                        - key: delta_step_count
                          value: '0'
                        - key: rotation_matrix
                          value: >-
                            0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
                    status: unverified
                    created_at: '2021-01-16T01:09:06.552Z'
                    updated_at: '2021-01-16T01:09:06.552Z'
                  - id: 8d6d82ab-532e-4e82-9d8c-60816bb2e588
                    reference_id: '213080'
                    image_url: nothing
                    lat: '1.3425'
                    lon: '34.342'
                    planter_id: '227'
                    planter_contact: treetr@gmail.com
                    attributes:
                      entries:
                        - key: dbh
                          value: ''
                        - key: abs_step_count
                          value: '-1'
                        - key: delta_step_count
                          value: '0'
                        - key: rotation_matrix
                          value: >-
                            0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
                    status: unverified
                    created_at: '2021-01-16T00:31:19.544Z'
                    updated_at: '2021-01-16T00:31:19.544Z'
                type: array
                items: {}
                description: An array of Capture objects
              example:
                - id: 870a77da-b8e1-4996-8636-f5f2602bf3f2
                  reference_id: '213103'
                  image_url: nothing
                  lat: '1.3425'
                  lon: '34.342'
                  planter_id: '227'
                  planter_contact: tree@gmail.com
                  attributes:
                    entries:
                      - key: dbh
                        value: ''
                      - key: abs_step_count
                        value: '-1'
                      - key: delta_step_count
                        value: '0'
                      - key: rotation_matrix
                        value: >-
                          0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
                  status: unverified
                  created_at: '2021-01-18T20:50:19.282Z'
                  updated_at: '2021-01-18T20:50:19.282Z'
                - id: 59de44f4-9a57-4de1-ae4f-e85cd330f4cd
                  reference_id: '213084'
                  image_url: nothing
                  lat: '1.3425'
                  lon: '34.342'
                  planter_id: '227'
                  planter_contact: verify@gmail.com
                  attributes:
                    entries:
                      - key: dbh
                        value: ''
                      - key: abs_step_count
                        value: '-1'
                      - key: delta_step_count
                        value: '0'
                      - key: rotation_matrix
                        value: >-
                          0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
                  status: unverified
                  created_at: '2021-01-16T01:39:37.423Z'
                  updated_at: '2021-01-16T01:39:37.423Z'
                - id: d6d6e901-f7eb-49ab-bf78-44727bd18e8b
                  reference_id: '213083'
                  image_url: nothing
                  lat: '1.3425'
                  lon: '34.342'
                  planter_id: '227'
                  planter_contact: gstracker@gmail.com
                  attributes:
                    entries:
                      - key: dbh
                        value: ''
                      - key: abs_step_count
                        value: '-1'
                      - key: delta_step_count
                        value: '0'
                      - key: rotation_matrix
                        value: >-
                          0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
                  status: unverified
                  created_at: '2021-01-16T01:37:01.046Z'
                  updated_at: '2021-01-16T01:37:01.046Z'
                - id: 5d288bde-463f-4a18-8529-d9e111a03d43
                  reference_id: '213082'
                  image_url: nothing
                  lat: '1.3425'
                  lon: '34.342'
                  planter_id: '227'
                  planter_contact: measure@gmail.com
                  attributes:
                    entries:
                      - key: dbh
                        value: ''
                      - key: abs_step_count
                        value: '-1'
                      - key: delta_step_count
                        value: '0'
                      - key: rotation_matrix
                        value: >-
                          0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
                  status: unverified
                  created_at: '2021-01-16T01:09:57.604Z'
                  updated_at: '2021-01-16T01:09:57.604Z'
                - id: cd2cbfa8-7203-41aa-966f-b844167e8df3
                  reference_id: '213081'
                  image_url: nothing
                  lat: '1.3425'
                  lon: '34.342'
                  planter_id: '227'
                  planter_contact: growth@gmail.com
                  attributes:
                    entries:
                      - key: dbh
                        value: ''
                      - key: abs_step_count
                        value: '-1'
                      - key: delta_step_count
                        value: '0'
                      - key: rotation_matrix
                        value: >-
                          0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
                  status: unverified
                  created_at: '2021-01-16T01:09:06.552Z'
                  updated_at: '2021-01-16T01:09:06.552Z'
                - id: 8d6d82ab-532e-4e82-9d8c-60816bb2e588
                  reference_id: '213080'
                  image_url: nothing
                  lat: '1.3425'
                  lon: '34.342'
                  planter_id: '227'
                  planter_contact: treetr@gmail.com
                  attributes:
                    entries:
                      - key: dbh
                        value: ''
                      - key: abs_step_count
                        value: '-1'
                      - key: delta_step_count
                        value: '0'
                      - key: rotation_matrix
                        value: >-
                          0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
                  status: unverified
                  created_at: '2021-01-16T00:31:19.544Z'
                  updated_at: '2021-01-16T00:31:19.544Z'
              type: array
              items: {}
              description: An array of Capture objects
          x-last-modified: 1611168768055
    post:
      tags: []
    patch:
      tags: []
    x-last-modified: 1611166894472
components:
  schemas:
    Capture:
      description: >-
        Represents the snapshot of a tree captured by a device with its
        associated data and meta data. It contains the photo of the tree,
        location, planter details.
      type: object
      properties:
        id:
          type: string
          minLength: 1
          description: >-
            The identifier for the capture record. The id is a valid UUID
            string.
          format: uuid
        reference_id:
          type: string
          minLength: 1
          description: >-
            A backward compatible integer identifier used and owned as primary
            key by the legacy `trees` table in main treetracker db for its row.
            This is a temporary reference during the data migration process and
            can be removed when migration is complete.
        image_url:
          type: string
          minLength: 1
          description: The url containing the tree image that represents the capture.
        lat:
          type: string
          minLength: 1
          description: |
            The latitude location value of the tree capture.
        lon:
          type: string
          minLength: 1
          description: The longitude location value of the tree capture.
        gps_accuracy: {}
        planter_id:
          type:
            - string
            - integer
          minLength: 1
          description: The identifier of the planter record associated with this capture.
        planter_photo_url:
          type: string
        planter_contact:
          type: string
        device_identifier:
          type: string
        note:
          type: string
        attributes:
          type: object
          required:
            - entries
          properties:
            entries:
              type: array
              uniqueItems: true
              minItems: 1
              items:
                type: object
                properties:
                  key:
                    type: string
                    minLength: 1
                  value:
                    type: string
                required:
                  - key
                  - value
        status:
          type: string
          minLength: 1
        created_at:
          type: string
          minLength: 1
        updated_at:
          type: string
          minLength: 1
      required:
        - id
        - image_url
        - lat
        - lon
        - planter_id
        - planter_contact
        - device_identifier
        - attributes
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes: {}
  links: {}
  callbacks: {}
security: []
tags: []
