name: CI for New Pull Requests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  project-directory: ./

jobs:
  build:
    name: Run all tests
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.project-directory }}

      - name: Install db-migrate
        run: npm install db-migrate
        working-directory: ${{ env.project-directory }}

      - name: run db-migrate
        run: npm run db-migrate-ci
        working-directory: ${{ env.project-directory }}
        env:
          DATABASE_URL: postgresql://postgres:postgres@postgres/postgres

      - name: run api-tests
        run: npm run test-api
        working-directory: ${{ env.project-directory }}
        env:
          DATABASE_URL: postgresql://postgres:postgres@postgres/postgres
          DATABASE_URL_MAINDB: postgresql://postgres:postgres@postgres/postgres
          CI: true
